#Name of the application
spring:
  application:
    name: ZuulService

#Eureka server url for registering
#This is eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#register url to server    

instance:
  hostname: localhost
  
server:
  port: 8989
  
zuul:
#  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  prefix: /onlineStore
  routes:
#    userAccessService:
#      path: /userservice/**
#      service-id: USERACCESSSERVICE
    consumerService:
      path: /consumerService/**
      service-id: CONSUMERSERVICE
    producerService:
      path: /producerService/**
      service-id: PRODUCERSERVICE
    itemService:
      path: /itemService/**
      service-id: ITEMSERVICE
    cartService:
      path: /cartService/**
      service-id: CARTSERVICE

      
      